import { buscarUrlBandera } from '../utils/buscarUrlBandera.js';

// Paletas pensadas para el diseño del frontend_usuario.
// colorPrincipal = fondo de página, colorAcento1/colorAcento2 = formas decorativas,
// colorTitulo = texto principal sobre colorPrincipal.

export const TEAM_VISUALS = {
    ALG: {
        asociacion: 'Fédération Algérienne de Football',
        colorPrincipal: '#0A8F43',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#D21034',
        colorTitulo: '#FFFFFF',
        grupo: 'J',
    },
    ARG: {
        asociacion: 'Asociación del Fútbol Argentino',
        colorPrincipal: '#75AADB',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#F6B40E',
        colorTitulo: '#082A5E',
        grupo: 'J',
    },
    AUS: {
        asociacion: 'Football Australia',
        colorPrincipal: '#FFCD00',
        colorAcento1: '#00843D',
        colorAcento2: '#002664',
        colorTitulo: '#003B2F',
        grupo: 'D',
    },
    AUT: {
        asociacion: 'Österreichischer Fußball-Bund',
        colorPrincipal: '#EF3340',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#111111',
        colorTitulo: '#FFFFFF',
        grupo: 'J',
    },
    BEL: {
        asociacion: 'Royal Belgian Football Association',
        colorPrincipal: '#ED2939',
        colorAcento1: '#FAE042',
        colorAcento2: '#000000',
        colorTitulo: '#FFFFFF',
        grupo: 'G',
    },
    BIH: {
        asociacion: 'Football Association of Bosnia and Herzegovina',
        colorPrincipal: '#005EB8',
        colorAcento1: '#FECB00',
        colorAcento2: '#FFFFFF',
        colorTitulo: '#FFFFFF',
        grupo: 'B',
    },
    BRA: {
        asociacion: 'Confederação Brasileira de Futebol',
        colorPrincipal: '#FFDF00',
        colorAcento1: '#009C3B',
        colorAcento2: '#002776',
        colorTitulo: '#003300',
        grupo: 'C',
    },
    CPV: {
        asociacion: 'Federação Caboverdiana de Futebol',
        colorPrincipal: '#003893',
        colorAcento1: '#CF2027',
        colorAcento2: '#F7D116',
        colorTitulo: '#FFFFFF',
        grupo: 'H',
    },
    CAN: {
        asociacion: 'Canadian Soccer Association',
        colorPrincipal: '#D80621',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#111111',
        colorTitulo: '#FFFFFF',
        grupo: 'B',
    },
    COL: {
        asociacion: 'Federación Colombiana de Fútbol',
        colorPrincipal: '#FCD116',
        colorAcento1: '#003893',
        colorAcento2: '#CE1126',
        colorTitulo: '#082A5E',
        grupo: 'K',
    },
    COD: {
        asociacion: 'Fédération Congolaise de Football-Association',
        colorPrincipal: '#007FFF',
        colorAcento1: '#F7D618',
        colorAcento2: '#CE1021',
        colorTitulo: '#FFFFFF',
        grupo: 'K',
    },
    CIV: {
        asociacion: 'Fédération Ivoirienne de Football',
        colorPrincipal: '#F77F00',
        colorAcento1: '#009E60',
        colorAcento2: '#FFFFFF',
        colorTitulo: '#FFFFFF',
        grupo: 'E',
    },
    CRO: {
        asociacion: 'Croatian Football Federation',
        colorPrincipal: '#FF0000',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#171796',
        colorTitulo: '#FFFFFF',
        grupo: 'L',
    },
    CUW: {
        asociacion: 'Curaçao Football Federation',
        colorPrincipal: '#002B7F',
        colorAcento1: '#F9E814',
        colorAcento2: '#FFFFFF',
        colorTitulo: '#FFFFFF',
        grupo: 'E',
    },
    CZE: {
        asociacion: 'Football Association of the Czech Republic',
        colorPrincipal: '#D7141A',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#11457E',
        colorTitulo: '#FFFFFF',
        grupo: 'A',
    },
    ECU: {
        asociacion: 'Federación Ecuatoriana de Fútbol',
        colorPrincipal: '#FFDD00',
        colorAcento1: '#034EA2',
        colorAcento2: '#ED1C24',
        colorTitulo: '#082A5E',
        grupo: 'E',
    },
    EGY: {
        asociacion: 'Egyptian Football Association',
        colorPrincipal: '#CE1126',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#000000',
        colorTitulo: '#FFFFFF',
        grupo: 'G',
    },
    ENG: {
        asociacion: 'The Football Association',
        colorPrincipal: '#FFFFFF',
        colorAcento1: '#CF142B',
        colorAcento2: '#00247D',
        colorTitulo: '#111111',
        grupo: 'L',
    },
    FRA: {
        asociacion: 'Fédération Française de Football',
        colorPrincipal: '#0055A4',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#EF4135',
        colorTitulo: '#FFFFFF',
        grupo: 'I',
    },
    GER: {
        asociacion: 'Deutscher Fußball-Bund',
        colorPrincipal: '#FFFFFF',
        colorAcento1: '#DD0000',
        colorAcento2: '#FFCE00',
        colorTitulo: '#111111',
        grupo: 'E',
    },
    GHA: {
        asociacion: 'Ghana Football Association',
        colorPrincipal: '#FCD116',
        colorAcento1: '#006B3F',
        colorAcento2: '#CE1126',
        colorTitulo: '#111111',
        grupo: 'L',
    },
    HAI: {
        asociacion: 'Fédération Haïtienne de Football',
        colorPrincipal: '#00209F',
        colorAcento1: '#D21034',
        colorAcento2: '#FFFFFF',
        colorTitulo: '#FFFFFF',
        grupo: 'C',
    },
    IRN: {
        asociacion: 'Football Federation Islamic Republic of Iran',
        colorPrincipal: '#239F40',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#DA0000',
        colorTitulo: '#FFFFFF',
        grupo: 'G',
    },
    IRQ: {
        asociacion: 'Iraq Football Association',
        colorPrincipal: '#CE1126',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#000000',
        colorTitulo: '#FFFFFF',
        grupo: 'I',
    },
    JPN: {
        asociacion: 'Japan Football Association',
        colorPrincipal: '#FFFFFF',
        colorAcento1: '#BC002D',
        colorAcento2: '#1B2A6B',
        colorTitulo: '#111111',
        grupo: 'F',
    },
    JOR: {
        asociacion: 'Jordan Football Association',
        colorPrincipal: '#007A3D',
        colorAcento1: '#CE1126',
        colorAcento2: '#000000',
        colorTitulo: '#FFFFFF',
        grupo: 'J',
    },
    KOR: {
        asociacion: 'Korea Football Association',
        colorPrincipal: '#C60C30',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#003478',
        colorTitulo: '#FFFFFF',
        grupo: 'A',
    },
    MEX: {
        asociacion: 'Federación Mexicana de Fútbol',
        colorPrincipal: '#006847',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#CE1126',
        colorTitulo: '#FFFFFF',
        grupo: 'A',
    },
    MAR: {
        asociacion: 'Fédération Royale Marocaine de Football',
        colorPrincipal: '#C1272D',
        colorAcento1: '#006233',
        colorAcento2: '#FFFFFF',
        colorTitulo: '#FFFFFF',
        grupo: 'C',
    },
    NED: {
        asociacion: 'Royal Dutch Football Association',
        colorPrincipal: '#FF7F00',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#21468B',
        colorTitulo: '#111111',
        grupo: 'F',
    },
    NZL: {
        asociacion: 'New Zealand Football',
        colorPrincipal: '#111111',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#00247D',
        colorTitulo: '#FFFFFF',
        grupo: 'G',
    },
    NOR: {
        asociacion: 'Norwegian Football Federation',
        colorPrincipal: '#BA0C2F',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#00205B',
        colorTitulo: '#FFFFFF',
        grupo: 'I',
    },
    PAN: {
        asociacion: 'Federación Panameña de Fútbol',
        colorPrincipal: '#D21034',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#005293',
        colorTitulo: '#FFFFFF',
        grupo: 'L',
    },
    PAR: {
        asociacion: 'Asociación Paraguaya de Fútbol',
        colorPrincipal: '#D52B1E',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#0038A8',
        colorTitulo: '#FFFFFF',
        grupo: 'D',
    },
    POR: {
        asociacion: 'Federação Portuguesa de Futebol',
        colorPrincipal: '#006600',
        colorAcento1: '#FF0000',
        colorAcento2: '#FFCC00',
        colorTitulo: '#FFFFFF',
        grupo: 'K',
    },
    QAT: {
        asociacion: 'Qatar Football Association',
        colorPrincipal: '#8A1538',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#D4AF37',
        colorTitulo: '#FFFFFF',
        grupo: 'B',
    },
    KSA: {
        asociacion: 'Saudi Arabian Football Federation',
        colorPrincipal: '#006C35',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#D4AF37',
        colorTitulo: '#FFFFFF',
        grupo: 'H',
    },
    SCO: {
        asociacion: 'Scottish Football Association',
        colorPrincipal: '#005EB8',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#001F4D',
        colorTitulo: '#FFFFFF',
        grupo: 'C',
    },
    SEN: {
        asociacion: 'Fédération Sénégalaise de Football',
        colorPrincipal: '#00853F',
        colorAcento1: '#FDEF42',
        colorAcento2: '#E31B23',
        colorTitulo: '#FFFFFF',
        grupo: 'I',
    },
    RSA: {
        asociacion: 'South African Football Association',
        colorPrincipal: '#007A4D',
        colorAcento1: '#FFB612',
        colorAcento2: '#000000',
        colorTitulo: '#FFFFFF',
        grupo: 'A',
    },
    ESP: {
        asociacion: 'Real Federación Española de Fútbol',
        colorPrincipal: '#AA151B',
        colorAcento1: '#F1BF00',
        colorAcento2: '#0039A6',
        colorTitulo: '#FFFFFF',
        grupo: 'H',
    },
    SWE: {
        asociacion: 'Swedish Football Association',
        colorPrincipal: '#006AA7',
        colorAcento1: '#FECC00',
        colorAcento2: '#FFFFFF',
        colorTitulo: '#FFFFFF',
        grupo: 'F',
    },
    SUI: {
        asociacion: 'Swiss Football Association',
        colorPrincipal: '#D52B1E',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#111111',
        colorTitulo: '#FFFFFF',
        grupo: 'B',
    },
    TUN: {
        asociacion: 'Fédération Tunisienne de Football',
        colorPrincipal: '#E70013',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#111111',
        colorTitulo: '#FFFFFF',
        grupo: 'F',
    },
    TUR: {
        asociacion: 'Turkish Football Federation',
        colorPrincipal: '#E30A17',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#111111',
        colorTitulo: '#FFFFFF',
        grupo: 'D',
    },
    URU: {
        asociacion: 'Asociación Uruguaya de Fútbol',
        colorPrincipal: '#7BC8F6',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#FCD116',
        colorTitulo: '#082A5E',
        grupo: 'H',
    },
    USA: {
        asociacion: 'United States Soccer Federation',
        colorPrincipal: '#3C3B6E',
        colorAcento1: '#B22234',
        colorAcento2: '#FFFFFF',
        colorTitulo: '#FFFFFF',
        grupo: 'D',
    },
    UZB: {
        asociacion: 'Uzbekistan Football Association',
        colorPrincipal: '#0099B5',
        colorAcento1: '#FFFFFF',
        colorAcento2: '#1EB53A',
        colorTitulo: '#FFFFFF',
        grupo: 'K',
    }
};

export const DEFAULT_TEAM_VISUALS = {
    searchName: null,
    asociacion: 'Federación/Asociación nacional de fútbol',
    urlBandera: buscarUrlBandera('Soccerball.svg'),
    colorPrincipal: '#64748B',
    colorAcento1: '#CBD5E1',
    colorAcento2: '#334155',
    colorTitulo: '#FFFFFF',
};
